# Generated by Django 4.2.4 on 2023-09-19 14:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, verbose_name='label')),
                ('thumbnail', models.CharField(blank=True, max_length=128, null=True, verbose_name='thumbnail')),
                ('description', models.CharField(max_length=128, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Chapiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, verbose_name='label')),
                ('thumbnail', models.CharField(blank=True, max_length=128, null=True, verbose_name='thumbnail')),
                ('content', models.TextField()),
                ('chapiterNumber', models.CharField(default=uuid.UUID('8e3f4227-fabc-48d9-b296-f68030aa3b43'), editable=False, max_length=255)),
                ('nextChapiter', models.CharField(blank=True, max_length=128, null=True, verbose_name='nextChapiter')),
                ('previewChapiter', models.CharField(blank=True, max_length=128, null=True, verbose_name='previewChapiter')),
                ('tutorialField', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.tutorialfield')),
            ],
        ),
    ]
