# Generated by Django 4.2.4 on 2023-09-19 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, verbose_name='label')),
                ('thumbnail', models.CharField(blank=True, max_length=128, null=True, verbose_name='thumbnail')),
                ('description', models.CharField(max_length=128, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='PostContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('nextPost', models.CharField(blank=True, max_length=128, null=True, verbose_name='nextPost')),
                ('previewPost', models.CharField(blank=True, max_length=128, null=True, verbose_name='previewPost')),
                ('blogPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost')),
            ],
        ),
    ]
