# Generated by Django 4.2.4 on 2023-09-15 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, verbose_name='label')),
                ('thumbnail', models.CharField(max_length=128, verbose_name='thumbnail')),
                ('description', models.CharField(max_length=128, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Chapiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, verbose_name='label')),
                ('thumbnail', models.CharField(max_length=128, verbose_name='thumbnail')),
                ('content', models.CharField(max_length=2000, verbose_name='content')),
                ('chapiterNumber', models.IntegerField()),
                ('nextChapiter', models.IntegerField()),
                ('previewChapiter', models.IntegerField()),
                ('tutorialField', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.tutorialfield')),
            ],
        ),
    ]
