# Generated by Django 4.2.4 on 2023-09-17 08:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0005_alter_chapiter_nextchapiter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapiter',
            name='chapiterNumber',
            field=models.CharField(default=uuid.UUID('fe5e770f-6103-4a4d-9532-e5c14ada84d1'), editable=False, max_length=255),
        ),
    ]
