# Generated by Django 4.2.4 on 2023-09-18 22:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0007_alter_chapiter_chapiternumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, verbose_name='label')),
                ('thumbnail', models.CharField(max_length=128, verbose_name='thumbnail')),
                ('description', models.CharField(max_length=128, verbose_name='description')),
            ],
        ),
        migrations.AlterField(
            model_name='chapiter',
            name='chapiterNumber',
            field=models.CharField(default=uuid.UUID('5b548f34-e365-43f4-9457-276c24e475a0'), editable=False, max_length=255),
        ),
        migrations.CreateModel(
            name='PostContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('nextPost', models.CharField(blank=True, max_length=128, null=True, verbose_name='nextPost')),
                ('previewPost', models.CharField(blank=True, max_length=128, null=True, verbose_name='previewPost')),
                ('blogPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.blogpost')),
            ],
        ),
    ]
