# Generated by Django 4.2.4 on 2023-09-19 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0009_alter_blogpost_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapiter',
            name='tutorialField',
        ),
        migrations.RemoveField(
            model_name='postcontent',
            name='blogPost',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='Chapiter',
        ),
        migrations.DeleteModel(
            name='PostContent',
        ),
        migrations.DeleteModel(
            name='TutorialField',
        ),
    ]
